<?php

namespace ContainerLTaILNd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZO6eemZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZO6eemZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZO6eemZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'bank' => ['privates', '.errored..service_locator.ZO6eemZ.App\\Entity\\Bank', NULL, 'Cannot autowire service ".service_locator.ZO6eemZ": it references class "App\\Entity\\Bank" but no such service exists.'],
        ], [
            'bank' => 'App\\Entity\\Bank',
        ]);
    }
}
