<?php

namespace ContainerLTaILNd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0LURLUVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0LURLUV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0LURLUV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\BankController::delete' => ['privates', '.service_locator.KUt9nTy', 'get_ServiceLocator_KUt9nTyService', true],
            'App\\Controller\\BankController::edit' => ['privates', '.service_locator.KUt9nTy', 'get_ServiceLocator_KUt9nTyService', true],
            'App\\Controller\\BankController::index' => ['privates', '.service_locator.DSZ8z7P', 'get_ServiceLocator_DSZ8z7PService', true],
            'App\\Controller\\BankController::new' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\BankController::show' => ['privates', '.service_locator.ZO6eemZ', 'get_ServiceLocator_ZO6eemZService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Controller\\BankController:delete' => ['privates', '.service_locator.KUt9nTy', 'get_ServiceLocator_KUt9nTyService', true],
            'App\\Controller\\BankController:edit' => ['privates', '.service_locator.KUt9nTy', 'get_ServiceLocator_KUt9nTyService', true],
            'App\\Controller\\BankController:index' => ['privates', '.service_locator.DSZ8z7P', 'get_ServiceLocator_DSZ8z7PService', true],
            'App\\Controller\\BankController:new' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\BankController:show' => ['privates', '.service_locator.ZO6eemZ', 'get_ServiceLocator_ZO6eemZService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
        ], [
            'App\\Controller\\BankController::delete' => '?',
            'App\\Controller\\BankController::edit' => '?',
            'App\\Controller\\BankController::index' => '?',
            'App\\Controller\\BankController::new' => '?',
            'App\\Controller\\BankController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\BankController:delete' => '?',
            'App\\Controller\\BankController:edit' => '?',
            'App\\Controller\\BankController:index' => '?',
            'App\\Controller\\BankController:new' => '?',
            'App\\Controller\\BankController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
