<?php

namespace ContainerLTaILNd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBank2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ZO6eemZ.App\Entity\Bank' shared service.
     *
     * @return \App\Entity\Bank
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.ZO6eemZ": it references class "App\\Entity\\Bank" but no such service exists.');
    }
}
