<?php

namespace ContainerPTgFUbI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DSZ8z7PService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DSZ8z7P' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DSZ8z7P'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'bankRepository' => ['privates', 'App\\Repository\\BankRepository', 'getBankRepositoryService', true],
        ], [
            'bankRepository' => 'App\\Repository\\BankRepository',
        ]);
    }
}
