<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGGBRcMP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGGBRcMP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGGBRcMP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGGBRcMP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGGBRcMP\App_KernelDevDebugContainer([
    'container.build_hash' => 'GGBRcMP',
    'container.build_id' => '8a6fc803',
    'container.build_time' => 1723081182,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGGBRcMP');
