<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLTaILNd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLTaILNd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLTaILNd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLTaILNd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLTaILNd\App_KernelDevDebugContainer([
    'container.build_hash' => 'LTaILNd',
    'container.build_id' => '64149e03',
    'container.build_time' => 1722851522,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLTaILNd');
